<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="2" time="0.079" timestamp="2024-08-10T23:54:10.477108+00:00" hostname="fv-az926-535"><testcase classname="tests.test_something" name="test_somefunction_42" time="0.002" /><testcase classname="tests.test_something" name="test_fail" time="0.001"><failure message="Failed: Failing on purpose">def test_fail():
&gt;       pytest.fail("Failing on purpose")
E       Failed: Failing on purpose

tests/test_something.py:12: Failed</failure></testcase></testsuite></testsuites>